### ISSUE TITLE
Build Issues on macOS 11

### ISSUE THREAD

**Issue by obelisk** [iqlusioninc/keychain-services-rs#25]
Trying to run the tests on macOS Big Sur fails with a linking error that is basically unable to find any of the symbols in `keychain_services::attr::KeyAttr`.

I dug through the Security framework in the dyld cache and I didn't see them there. The references I can find to these are that they are an enum but the code seems to suggest they are CFStringRefs.

Any help on getting this compiling would be helpful!

**Comment by obelisk** [comment]
Commenting out the function works but I wonder where those symbols went, or if they were ever there?

**Comment by tony-iqlusion** [comment]
It's been awhile since a build has succeeded in CI. It's possible something has changed.

We haven't actively used this library in awhile and it may no longer be working on recent builds of macOS.

It'd be good to get the CI moved over to GitHub Actions.
